BUILD_DIR=.
SRC_DIR=$(BUILD_DIR)/src
CC=g++
RM=rm
TEST_SRCS=cxxlin_test.cxx
TEST_OBJS=cxxlin_test.o
TEST_OUTPUT=cxxlin_test
DEFINE_FLAGS_DEBUG=-DDEBUG
DEFINE_FLAGS_RELEASE=-DRELEASE
CC_TEST_FLAGS=-c -std=c++14
CC_TEST_FLAGS_DEBUG=$(CC_TEST_FLAGS) -g $(DEFINE_FLAGS_DEBUG) -Wno-write-strings
CC_TEST_FLAGS_RELEASE=$(CC_TEST_FLAGS) $(DEFINE_FLAGS_RELEASE) -O3
CC_TEST_SRCS=$(addprefix $(SRC_DIR)/,$(TEST_SRCS))
TEST_LINKER_OPTIONS=`sdl2-config --cflags --libs` -lGL
CC_TEST_OBJS=$(addprefix $(BUILD_DIR)/,$(TEST_OBJS))
CC_TEST_OUT=-o $(TEST_OUTPUT)
CLEAN_TEST_OBJS=$(CC_TEST_OBJS)
CLEAN_TEST_OUT=$(addprefix $(BUILD_DIR)/,$(TEST_OUTPUT))

all: objs
	$(CC) $(CC_TEST_OBJS) $(CC_TEST_OUT) $(TEST_LINKER_OPTIONS) 

debug: debugobjs
	$(CC) $(CC_TEST_OBJS) $(CC_TEST_OUT) $(TEST_LINKER_OPTIONS)

debugobjs:
	$(CC) $(CC_TEST_FLAGS_DEBUG) $(CC_TEST_SRCS) $(TEST_LINKER_OPTIONS)

objs:
	$(CC) $(CC_TEST_FLAGS_RELEASE) $(CC_TEST_SRCS) $(TEST_LINKER_OPTIONS)

clean:
	-$(RM) $(CLEAN_TEST_OBJS)

cleanall: clean
	-$(RM) $(CLEAN_TEST_OUT)
